### PR TITLE
Update to psc 0.9.1

### PR DESCRIPTION
**Pull request by adkelley**
- Changes to support psc 0.9.1
- Created public directory
- index.html  -> ./public/html/
- Main.js -> ./public/scripts/
- Updated package.json to remove webpack dependency
- Updated Readme to document psc 0.9.1 support, and build change from webpack to browserify

### CODE REVIEW

**Comment by ethul** [comment]
Thanks for the update!

One quick item: Do you think we need to check in the contents of `public/scripts`?

**Comment by adkelley** [comment]
No, we should not check in `public/scripts`  Sorry that folder should have been included in my `.gitignore` file.  Also, I'll get rid of the `public/html` folder and move index.html directly under public/  I'll issue another PR with those changes.  Standby

**Comment by ethul** [comment]
Thanks!

**Comment by adkelley** [comment]
Hold on! - the `public/scripts` folder got deleted together with the `scripts/Main.js`  I need to change .gitignore.  Standby for one more commit.

**Comment by adkelley** [comment]
Ok.  Done!

**Comment by ethul** [comment]
Great! Thanks again

**Pull request merged**
